### ISSUE TITLE
multipart/mixed - ** (ArgumentError) argument error     :erlang.iolist_to_iovec

### ISSUE THREAD

**Issue by ponty96** [breakroom/multipart#1]
I tried the example in the Readme and I got this error:

```elixir
  multipart =
  Multipart.new()
  |> Multipart.add_part(Multipart.Part.binary_body("first body"))
  |> Multipart.add_part(Multipart.Part.binary_body("second body", [{"content-type", "text/plain"}]))
  |> Multipart.add_part(Multipart.Part.binary_body("<p>third body</p>", [{"content-type", "text/html"}]))

  body_stream = Multipart.body_stream(multipart) |> IO.inspect
  content_length = Multipart.content_length(multipart)
  content_type = Multipart.content_type(multipart, "multipart/mixed; boundary=mimeboundary")

  token = Base.encode64("username:password")
  headers = [{"Content-Type", "multipart/mixed; boundary=mimeboundary"}, {"Content-Length", "#{content_length}"}, {"Authorization", "Basic #{token}"}]

  Finch.build("POST", url, headers,  body_stream)  |> Finch.request(MyFinch)
```

```elixir
** (ArgumentError) argument error
    :erlang.iolist_to_iovec([["POST", 32, "/mms/v2/send", " HTTP/1.1\r\n"], [[[[["", "host", ": ", "mms.example.com", "\r\n"], "user-agent", ": ", "mint/1.2.1", "\r\n"], "content-type", ": ", "multipart/mixed; boundary=mimeboundary", "\r\n"], "content-length", ": ", "42", "\r\n"], "authorization", ": ", "Basic ZGRkZERkZWV3OnNvbWVwYXNz=", "\r\n"], "\r\n", #Function<62.38660007/2 in Stream.transform/3>])
    (ssl 9.6.1) ssl.erl:834: :ssl.send/2
    (mint 1.2.1) lib/mint/core/transport/ssl.ex:368: Mint.Core.Transport.SSL.send/2
    (mint 1.2.1) lib/mint/http1.ex:248: Mint.HTTP1.request/5
    (finch 0.4.0) lib/finch/http1/conn.ex:96: Finch.Conn.request/5
    (finch 0.4.0) lib/finch/http1/pool.ex:43: anonymous fn/8 in Finch.HTTP1.Pool.request/5
    (nimble_pool 0.2.4) lib/nimble_pool.ex:266: NimblePool.checkout!/4
    (finch 0.4.0) lib/finch/http1/pool.ex:36: Finch.HTTP1.Pool.request/5
    (finch 0.4.0) lib/finch.ex:207: Finch.request/3
```

**Comment by tomtaylor** [comment]
This looks a bit like your connection to `mms.example.com` isn't working. I'm going to close this, but please reopen if you think it's still a valid issue.
